-- Register dm-prod OAuth2 business client in xinyi-platform (superseded by auto-registration).
-- As of 2026-06-25, docupipe-manager auto-registers via register_self() on startup.
-- This script is kept for reference only; the old docupipe-prod record can be deleted
-- after the first auto-registration as dm-prod:
--   DELETE FROM xinyi.business_clients WHERE client_id = 'docupipe-prod';
